name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.TARGET.OS }}
    strategy:
      fail-fast: false
      matrix:
        TARGET:
          - {
              OS: 'ubuntu-latest',
              CFLAGS: '-static -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0',
              HOST: 'i386-pc-linux',
              ARCHIVE_NAME: 'binutils-2.7.tar.gz'
            }

    name: Building binutils for ${{ matrix.TARGET.OS }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        shell: bash
        if: matrix.TARGET.OS == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bison file gperf
      - name: Configure for mips
        shell: bash
        run: |
          ./configure --target=mips-mips-elf --prefix=/opt/cross --disable-gprof --disable-gdb --disable-werror --host=${{ matrix.TARGET.HOST }} --build=${{ matrix.TARGET.HOST }}
      - name: Make
        continue-on-error: true
        shell: bash
        run: |
          make CFLAGS="${{ matrix.TARGET.CFLAGS }}"
          sudo make install
      - name: Test for file
        shell: bash
        run: |
          test -f binutils/ar
          file binutils/ar
          test -f binutils/strip.new
          file binutils/strip.new
      - name: Create release archive
        shell: bash
        run: |
          cp /opt/cross/bin/mips-mips-elf-ar ar
          strip ar
          chmod +x ar
          cp /opt/cross/bin/mips-mips-elf-strip strip-2.7
          strip strip-2.7
          chmod +x strip-2.7
          tar -czf ${{ matrix.TARGET.ARCHIVE_NAME }} strip-2.7 ar
      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: binutils-2.7-${{ matrix.TARGET.OS }}
          path: |
            ${{ matrix.TARGET.ARCHIVE_NAME }}
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ${{ matrix.TARGET.ARCHIVE_NAME }}
